language: c
arch:
 - amd64
 - ppc64le

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      osx_image: xcode11

script:
  - cd ${TRAVIS_BUILD_DIR}
  - FAKETIME_COMPILE_CFLAGS="-DFORCE_MONOTONIC_FIX" make
  - make test
